"""Strict state for bounded conversational semantic melding.

The package preserves the historical ``meld.model`` API while assigning frozen
sources, relation review, exact changes, and session lifecycle to explicit
Meld-owned modules.
"""

from .changes import MeldApplication, MeldChangeSet, MeldCheckpointReceipt
from .relation_review import (
    MeldAssessment,
    MeldIssue,
    MeldMember,
    MeldOption,
    MeldProposal,
    MeldRelation,
    MeldTurn,
    default_meld_revision,
    directional_comparison_basis_assessment,
    meld_turn_evidence_payload,
    validate_meld_turn_lineage,
)
from .session import (
    MeldAccounting,
    MeldSession,
    inline_meld_context,
    materialize_preservation_assessment,
    meld_accounting,
)
from .source_frames import (
    INLINE_MELD_CONTEXT_NAME,
    MELD_COMPARISON_SCHEMA_VERSION,
    MELD_DIRECTIONAL_COMPARISON_SCHEMA_VERSION,
    MELD_DIRECTIONAL_PRESERVATION_SCHEMA_VERSION,
    MELD_GRANTED_SCHEMA_VERSION,
    MELD_ID_LIMIT,
    MELD_INLINE_MEMORY_SCHEMA_VERSION,
    MELD_LEGACY_SCHEMA_VERSION,
    MELD_MEMORY_FOCUS_SCHEMA_VERSION,
    MELD_NAME_LIMIT,
    MELD_OWNER_AWARE_SCHEMA_VERSION,
    MELD_SCHEMA_VERSION,
    MELD_TEXT_LIMIT,
    MeldComparisonSeed,
    MeldDisposition,
    MeldError,
    MeldFrame,
    MeldIssuePriority,
    MeldMemory,
    MeldMode,
    MeldProposalOperation,
    MeldRelationKind,
    MeldRelationStatus,
    MeldRepairableAssessmentError,
    MeldRevision,
    MeldRole,
    MeldState,
    MeldTarget,
    MeldTurnScope,
    meld_canonical_digest,
)

__all__ = (
    "INLINE_MELD_CONTEXT_NAME",
    "MELD_COMPARISON_SCHEMA_VERSION",
    "MELD_DIRECTIONAL_COMPARISON_SCHEMA_VERSION",
    "MELD_DIRECTIONAL_PRESERVATION_SCHEMA_VERSION",
    "MELD_GRANTED_SCHEMA_VERSION",
    "MELD_ID_LIMIT",
    "MELD_INLINE_MEMORY_SCHEMA_VERSION",
    "MELD_LEGACY_SCHEMA_VERSION",
    "MELD_MEMORY_FOCUS_SCHEMA_VERSION",
    "MELD_NAME_LIMIT",
    "MELD_OWNER_AWARE_SCHEMA_VERSION",
    "MELD_SCHEMA_VERSION",
    "MELD_TEXT_LIMIT",
    "MeldAccounting",
    "MeldApplication",
    "MeldAssessment",
    "MeldChangeSet",
    "MeldCheckpointReceipt",
    "MeldComparisonSeed",
    "MeldDisposition",
    "MeldError",
    "MeldFrame",
    "MeldIssue",
    "MeldIssuePriority",
    "MeldMember",
    "MeldMemory",
    "MeldMode",
    "MeldOption",
    "MeldProposal",
    "MeldProposalOperation",
    "MeldRelation",
    "MeldRelationKind",
    "MeldRelationStatus",
    "MeldRepairableAssessmentError",
    "MeldRevision",
    "MeldRole",
    "MeldSession",
    "MeldState",
    "MeldTarget",
    "MeldTurn",
    "MeldTurnScope",
    "default_meld_revision",
    "directional_comparison_basis_assessment",
    "inline_meld_context",
    "materialize_preservation_assessment",
    "meld_accounting",
    "meld_canonical_digest",
    "meld_turn_evidence_payload",
    "validate_meld_turn_lineage",
)
