"""Blank-Ground shell contracts, presentation, and runtime."""

from memcommit.adapters.console.commands.ground_workbench.ground.shell.presentation import (
    render_ground_cases_pane,
    render_ground_contexts_pane,
    render_ground_goal_pane,
    render_ground_location_pane,
    render_ground_memories_pane,
    render_ground_rules_pane,
    render_ground_top_panel,
    render_ground_workspace_pane,
    render_proposal_review,
    _anchored_conversation_fragments as _anchored_conversation_fragments,
    _render_ground_memory_table as _render_ground_memory_table,
    _render_proposal_command_block as _render_proposal_command_block,
    _render_proposal_effects_block as _render_proposal_effects_block,
)
from memcommit.adapters.console.commands.ground_workbench.ground.shell.proposal import (
    GroundApplier,
    GroundInterpreter,
    GroundShellContextSuggestion,
    GroundShellMemoryDraft,
    GroundShellNewContextSuggestion,
    GroundShellProposal,
    GroundShellResult,
    GroundShellRuleDraft,
    format_proposal_command,
    proposal_argv,
    _field as _field,
    _freeze_context_suggestions as _freeze_context_suggestions,
    _freeze_memory_drafts as _freeze_memory_drafts,
    _freeze_new_context_suggestions as _freeze_new_context_suggestions,
    _freeze_proposal as _freeze_proposal,
    _freeze_rule_drafts as _freeze_rule_drafts,
    _freeze_source_spans as _freeze_source_spans,
    _proposal_review as _proposal_review,
    _required_text as _required_text,
    _response_kind as _response_kind,
)
from memcommit.adapters.console.commands.ground_workbench.ground.shell.runtime import (
    GROUND_CONTEXTS_FRAME_HEIGHT,
    GROUND_GOAL_FRAME_HEIGHT,
    GROUND_LOCATION_FRAME_HEIGHT,
    INITIAL_QUESTION,
    run_ground_shell,
)

__all__ = [
    "GROUND_CONTEXTS_FRAME_HEIGHT",
    "GROUND_GOAL_FRAME_HEIGHT",
    "GROUND_LOCATION_FRAME_HEIGHT",
    "INITIAL_QUESTION",
    "GroundApplier",
    "GroundInterpreter",
    "GroundShellContextSuggestion",
    "GroundShellMemoryDraft",
    "GroundShellNewContextSuggestion",
    "GroundShellProposal",
    "GroundShellResult",
    "GroundShellRuleDraft",
    "format_proposal_command",
    "proposal_argv",
    "render_ground_cases_pane",
    "render_ground_contexts_pane",
    "render_ground_goal_pane",
    "render_ground_location_pane",
    "render_ground_memories_pane",
    "render_ground_rules_pane",
    "render_ground_top_panel",
    "render_ground_workspace_pane",
    "render_proposal_review",
    "run_ground_shell",
]
