"""Audited public operation meanings used by every Help projection."""

from __future__ import annotations

from memcommit.help_catalog.model import ExecutionKind, OperationHelp


def _operation(
    name: str,
    summary: str,
    flow: str,
    execution: ExecutionKind,
    effect: str,
    range: str | None = None,
) -> OperationHelp:
    return OperationHelp(
        name=name,
        summary=summary,
        flow=flow,
        execution=execution,
        effect=effect,
        range=range,
    )


_OPERATIONS = (
    _operation(
        "add",
        "Add one or more Memories to the current or explicit Context.",
        "Text or file -> Context Memories",
        ExecutionKind.DETERMINISTIC,
        "Changes the selected Context",
        "One exact target Context",
    ),
    _operation(
        "atomize",
        "Split composite Memories for review; --evaluate performs an issue-scoped directional meld.",
        "Context Memories -> reviewed atomic Memories",
        ExecutionKind.SEMANTIC,
        "Changes material only after explicit acceptance",
        "One selected Context frame",
    ),
    _operation(
        "audit",
        "Run Duplicate, Ambiguity, and Conflict checks and review one saved report.",
        "Context -> saved quality report",
        ExecutionKind.SEMANTIC,
        "No Context content changes",
        "One exact direct Context",
    ),
    _operation(
        "branch",
        "Copy a Context or subtree into a new branch and switch to it.",
        "Context -> new Context branch",
        ExecutionKind.DETERMINISTIC,
        "Creates a Context and switches to it",
        "Source exact or lexical descendants",
    ),
    _operation(
        "checkout",
        "Switch Contexts using Git-style syntax; with -b, create and switch to a new Context branch.",
        "Context locator -> current Context or new branch",
        ExecutionKind.DETERMINISTIC,
        "Switches Context; -b also creates one",
        "Branch Source exact or lexical descendants",
    ),
    _operation(
        "checkpoint",
        "Save the current Context as a manual recovery point for Diff or Revert.",
        "Context state -> checkpoint",
        ExecutionKind.DETERMINISTIC,
        "Adds recoverable history; content is unchanged",
    ),
    _operation(
        "chunk",
        "Preview and split one direct Memory by headers, paragraphs, or sentences.",
        "Memory -> ordered Memory chunks",
        ExecutionKind.DETERMINISTIC,
        "Changes the Source Context after confirmation",
        "One direct Memory",
    ),
    _operation(
        "clear",
        "Remove all direct items from the current or explicit Context after confirmation.",
        "Context direct items -> empty Context",
        ExecutionKind.DETERMINISTIC,
        "Destructive Context change after confirmation",
        "One exact Context",
    ),
    _operation(
        "compare",
        "Compare two equal-authority Contexts without changing either one.",
        "Context <-> Context -> comparison report",
        ExecutionKind.SEMANTIC,
        "No Context content changes",
        "Each side exact or readable descendants",
    ),
    _operation(
        "config",
        "Read and write global configuration.",
        "Configuration key <-> value",
        ExecutionKind.DETERMINISTIC,
        "May change global configuration",
    ),
    _operation(
        "contexts",
        "Browse local Contexts and readable cross-Profile Context views without switching.",
        "Profile access -> readable Context catalog",
        ExecutionKind.DETERMINISTIC,
        "Read-only; current Context is unchanged",
        "All readable Context names",
    ),
    _operation(
        "delete",
        "Select a Context or direct item to delete, or name it by locator, name, or UID.",
        "Context or direct item -> removed",
        ExecutionKind.DETERMINISTIC,
        "Destructive change after confirmation",
        "One exact Context or direct item",
    ),
    _operation(
        "diff",
        "Inspect recorded Context or Update changes without applying them.",
        "Recorded change -> diff report",
        ExecutionKind.DETERMINISTIC,
        "Read-only",
        "One exact Context or active Update",
    ),
    _operation(
        "edit",
        "Replace direct Memory content by UID or prefix in the current or explicit Context.",
        "Memory -> replacement Memory content",
        ExecutionKind.DETERMINISTIC,
        "Changes one direct Memory",
        "One direct Memory in one exact Context",
    ),
    _operation(
        "embed",
        "Place a Child Context inside a target while retaining its identity and ownership.",
        "Child Context -> parent Context placement",
        ExecutionKind.DETERMINISTIC,
        "Changes target structure; Child identity is retained",
        "One Child and one exact target",
    ),
    _operation(
        "eval",
        "Run and inspect staged semantic evaluation campaigns.",
        "Evaluation fixtures -> campaign results",
        ExecutionKind.MIXED,
        "Changes evaluation ledgers, not Context content",
    ),
    _operation(
        "find",
        "Search selected Contexts with explicit lexical-descendant and embedded-Context reach.",
        "Context set + query -> ranked Memories",
        ExecutionKind.SEMANTIC,
        "Read-only search",
        "Selected roots; lexical and embedded reach are independent",
    ),
    _operation(
        "find-ambiguities",
        "Report ambiguous direct Memories in the current or explicit Context; no Context changes.",
        "Context Memories -> ambiguity report",
        ExecutionKind.SEMANTIC,
        "No Context content changes",
        "One exact direct Context",
    ),
    _operation(
        "find-conflicts",
        "Report conflicting direct Memory pairs in the current or explicit Context; no Context changes.",
        "Context Memories -> conflict report",
        ExecutionKind.SEMANTIC,
        "No Context content changes",
        "One exact direct Context",
    ),
    _operation(
        "find-duplicates",
        "Report duplicate direct Memories in the current or explicit Context; no Context changes.",
        "Context Memories -> duplicate report",
        ExecutionKind.SEMANTIC,
        "No Context content changes",
        "One exact direct Context",
    ),
    _operation(
        "forget",
        "Review keep/edit/delete decisions for one instruction, then apply the accepted batch.",
        "Context + instruction -> reviewed curation batch",
        ExecutionKind.SEMANTIC,
        "Changes Source only after reviewed acceptance",
        "One exact direct Source frame",
    ),
    _operation(
        "ground",
        "Create or continue a reviewed Goal-Rules-Memories Ground workbench.",
        "Dialogue + evidence -> reviewed Ground",
        ExecutionKind.SEMANTIC,
        "Changes Ground records; Context changes require separate commands",
    ),
    _operation(
        "help",
        "Enter the interactive command browser and open syntax help.",
        "Operation catalog -> usage guidance",
        ExecutionKind.DETERMINISTIC,
        "Read-only",
    ),
    _operation(
        "impact",
        "Preview or inspect operation Impact; no Context changes occur before its reviewed Apply handoff.",
        "Operation inputs or session -> impact report",
        ExecutionKind.MIXED,
        "Impact is read-only; Apply is a separate reviewed handoff",
        "Operation-owned Source and Target ranges",
    ),
    _operation(
        "import",
        "Import a clean-baseline Profile, Context tree, or Memory by value while preserving resource identity.",
        "External resource -> local owned copy",
        ExecutionKind.DETERMINISTIC,
        "Creates or changes local owned resources",
        "Profile, exact Context, subtree, or one Memory",
    ),
    _operation(
        "init",
        "Create a named Context, optionally ensure its parents, and switch to it.",
        "New Context name -> Context",
        ExecutionKind.DETERMINISTIC,
        "Creates a Context and switches to it",
        "One fresh exact name; optional lexical parents",
    ),
    _operation(
        "init-study",
        "Copy one Study baseline into an isolated participant/authority Profile pair.",
        "Study baseline -> isolated Study Profiles",
        ExecutionKind.DETERMINISTIC,
        "Creates isolated Profile stores and switches Profile",
    ),
    _operation(
        "list",
        "Browse child Contexts and direct items; ls is the equivalent compact spelling.",
        "Context -> Context and direct-item listing",
        ExecutionKind.DETERMINISTIC,
        "Read-only",
        "One exact Context or lexical descendants",
    ),
    _operation(
        "lock",
        "Lock the current Context, a recursive Context set, Memory, or Profile.",
        "Resource -> write-protected resource",
        ExecutionKind.DETERMINISTIC,
        "Changes protection metadata",
        "Exact resource or recursive Context set",
    ),
    _operation(
        "log",
        "Browse Context checkpoints, inspect one Memory lineage with --memory, search history, or list Profile command attempts.",
        "Recorded history or query -> history report",
        ExecutionKind.MIXED,
        "Read-only",
        "One Context, one Memory lineage, or Profile attempts",
    ),
    _operation(
        "meld",
        "Combine two equal-authority Contexts in the current empty Context; --from is normalized to INCOMING --into authoritative BASELINE.",
        "Context <-> Context or Incoming -> Baseline",
        ExecutionKind.SEMANTIC,
        "Creates or changes material only after reviewed Apply",
        "Each side exact or readable descendants",
    ),
    _operation(
        "merge",
        "Add UID-new items from an exact Source or path-aligned descendants; no semantic reconciliation.",
        "Source Context -> current Target Context",
        ExecutionKind.DETERMINISTIC,
        "Changes the Target Context tree directly; Source stays unchanged",
        "Exact roots or matching lexical descendants by complete relative path",
    ),
    _operation(
        "profile",
        "Enter the interactive Profile selector, or manage complete local MemoryStore Profiles.",
        "Profile registry <-> Profile administration",
        ExecutionKind.DETERMINISTIC,
        "May switch, create, import, rename, or remove Profiles",
    ),
    _operation(
        "provider",
        "Select and verify Codex, Ollama, or OpenRouter semantic execution.",
        "Provider configuration <-> status or probe",
        ExecutionKind.DETERMINISTIC,
        "May change provider configuration or make a probe request",
    ),
    _operation(
        "pwd",
        "Print the current canonical Context name without loading its contents.",
        "Current Context pointer -> canonical name",
        ExecutionKind.DETERMINISTIC,
        "Read-only; Context content is not loaded",
    ),
    _operation(
        "query",
        "Ask readable Context knowledge or an authorized concealed query-only view.",
        "Readable source + question -> answer with references",
        ExecutionKind.SEMANTIC,
        "No Context content changes; visible transcript may be retained",
        "Exact, descendants, embeds, or authorized query-only view",
    ),
    _operation(
        "rationale",
        "Explain one Memory from recorded provenance and, when needed, inference.",
        "Memory provenance -> rationale",
        ExecutionKind.MIXED,
        "Read-only",
        "One current or historical Memory",
    ),
    _operation(
        "redo",
        "Redo the most recently undone recorded Context command.",
        "Undo history -> restored command effects",
        ExecutionKind.DETERMINISTIC,
        "Changes the affected Context set",
    ),
    _operation(
        "reference",
        "Add a read-only Memory pointer; the Target stores identity metadata rather than copying content.",
        "Source Memory -> Target Context reference",
        ExecutionKind.DETERMINISTIC,
        "Adds reference metadata to the Target",
        "One direct Source Memory and one exact Target",
    ),
    _operation(
        "rename",
        "Rename the current or an explicit managed Profile without moving or rewriting its store; mem profile rename is the explicit equivalent.",
        "Managed Profile name -> new Profile name",
        ExecutionKind.DETERMINISTIC,
        "Changes registry metadata; store contents stay in place",
    ),
    _operation(
        "revert",
        "Select a checkpoint and review restoration of one local Context.",
        "Checkpoint -> restored Context state",
        ExecutionKind.MIXED,
        "Changes one Context after restoration review",
        "One exact local Context",
    ),
    _operation(
        "review",
        "Enter an interactive Review session or stage semantic review responses; never apply Memories.",
        "Saved analysis -> review responses",
        ExecutionKind.MIXED,
        "No Context content changes",
        "One saved operation artifact",
    ),
    _operation(
        "sever",
        "Review Source against Criteria and create a derived Result while leaving Source unchanged.",
        "Source Context + Criteria Context -> new Result Context",
        ExecutionKind.SEMANTIC,
        "Creates reviewed Result; Source remains unchanged",
        "Source exact or descendants; Criteria exact scoped frame",
    ),
    _operation(
        "share",
        "Send one ordinary Context through a grant-backed receiver endpoint.",
        "Owned Context -> receiver endpoint",
        ExecutionKind.DETERMINISTIC,
        "External delivery; Source remains unchanged",
        "One exact ordinary Source Context",
    ),
    _operation(
        "shell-init",
        "Print opt-in shell integration for interactive command prefill.",
        "Shell name -> integration script",
        ExecutionKind.DETERMINISTIC,
        "Read-only; installation requires explicit shell evaluation",
    ),
    _operation(
        "show",
        "Show a Memory, reference, embedded Context, or the direct contents of a current/explicit Context.",
        "Context or direct item -> rendered content",
        ExecutionKind.DETERMINISTIC,
        "Read-only",
        "One exact Context or direct item",
    ),
    _operation(
        "status",
        "Show current Context counts, recent Memories, and checkpoints.",
        "Current Context -> status report",
        ExecutionKind.DETERMINISTIC,
        "Read-only",
        "Current exact Context",
    ),
    _operation(
        "summarize",
        "Show what Mem understands from a Context's visible ordinary Memories.",
        "Context -> summary",
        ExecutionKind.SEMANTIC,
        "Read-only",
        "Exact Context or descendants plus embedded Contexts",
    ),
    _operation(
        "switch",
        "Enter the interactive Context picker, or switch to an explicit Context.",
        "Context locator -> current Context pointer",
        ExecutionKind.DETERMINISTIC,
        "Changes only the current Context pointer",
        "One exact existing Context",
    ),
    _operation(
        "trace",
        "Trace one retained Memory through its recorded lineage.",
        "Memory -> retained lineage",
        ExecutionKind.DETERMINISTIC,
        "Read-only",
        "One current or historical Memory",
    ),
    _operation(
        "translate",
        "Show and save a reusable translation view; materialize it only through an explicit route.",
        "Context or Memory -> translated view or materialization",
        ExecutionKind.SEMANTIC,
        "Source unchanged; explicit routes may create or add material",
        "One exact Context or one direct Memory",
    ),
    _operation(
        "undo",
        "Undo the most recent recorded Context command across its affected Contexts.",
        "Command history -> reversed Context effects",
        ExecutionKind.DETERMINISTIC,
        "Changes every Context affected by that command",
    ),
    _operation(
        "unlock",
        "Unlock the current Context, a recursive set, Memory, or Profile.",
        "Protected resource -> writable resource",
        ExecutionKind.DETERMINISTIC,
        "Changes protection metadata",
        "Exact resource or recursive Context set",
    ),
    _operation(
        "update",
        "Review a directional plan and apply it to a local target; no shared publication.",
        "Source Context -> Target Context",
        ExecutionKind.SEMANTIC,
        "Changes local Target only after reviewed Apply",
        "Each endpoint exact or readable descendants",
    ),
)


OPERATION_HELP_BY_NAME = {operation.name: operation for operation in _OPERATIONS}

if len(OPERATION_HELP_BY_NAME) != len(_OPERATIONS):  # pragma: no cover
    raise RuntimeError("Operation Help names must be unique.")


def operation_help(name: str) -> OperationHelp:
    """Return one audited operation contract or fail on an unknown name."""

    try:
        return OPERATION_HELP_BY_NAME[name]
    except KeyError as error:
        raise KeyError(f"No Operation Help is registered for {name!r}.") from error


def operation_summary(name: str) -> str:
    """Return the canonical one-line description used by interface adapters."""

    return operation_help(name).summary
