"""Stable public Python API for MemCommit."""

from memcommit.api.client import MemCommitClient
from memcommit.api.add import AddMemoriesResult, AddedMemoryResult
from memcommit.api.errors import (
    AddAuthorityError,
    AddConflictError,
    AddContextError,
    AddError,
    AddExecutionError,
    AddInputError,
    AddStorageError,
    MemCommitError,
    MeldAuthorityError,
    MeldConflictError,
    MeldContextError,
    MeldError,
    MeldExecutionError,
    MeldInputError,
    MeldProviderFailure,
    MeldStorageError,
    QueryAuthorityError,
    QueryConfigurationError,
    QueryContextError,
    QueryError,
    QueryExecutionError,
    QueryInputError,
    QueryProviderFailure,
    QueryPublicationError,
    QueryStorageError,
)
from memcommit.api.meld import (
    MeldApplyResult,
    MeldIssueResult,
    MeldOptionResult,
    MeldProposalResult,
    MeldSessionResult,
)
from memcommit.api.query import (
    GrantedQueryResult,
    OrdinaryQueryResult,
    QueryCatalogEntry,
    QueryCitation,
    QueryProviderConfig,
    QuerySessionReceipt,
    ReferenceQueryResult,
)

__all__ = [
    "AddAuthorityError",
    "AddConflictError",
    "AddContextError",
    "AddError",
    "AddExecutionError",
    "AddInputError",
    "AddMemoriesResult",
    "AddStorageError",
    "AddedMemoryResult",
    "GrantedQueryResult",
    "MemCommitClient",
    "MemCommitError",
    "MeldApplyResult",
    "MeldAuthorityError",
    "MeldConflictError",
    "MeldContextError",
    "MeldError",
    "MeldExecutionError",
    "MeldInputError",
    "MeldIssueResult",
    "MeldOptionResult",
    "MeldProposalResult",
    "MeldProviderFailure",
    "MeldSessionResult",
    "MeldStorageError",
    "OrdinaryQueryResult",
    "QueryAuthorityError",
    "QueryCatalogEntry",
    "QueryCitation",
    "QueryConfigurationError",
    "QueryContextError",
    "QueryError",
    "QueryExecutionError",
    "QueryInputError",
    "QueryProviderConfig",
    "QueryProviderFailure",
    "QueryPublicationError",
    "QuerySessionReceipt",
    "QueryStorageError",
    "ReferenceQueryResult",
]
