"""Stable public Python API for MemCommit.

The public names remain available from this module, but resolving one DTO or
client must not eagerly assemble every operation implementation.
"""

from importlib import import_module

__all__ = [
    "AddAuthorityError",
    "AddConflictError",
    "AddContextError",
    "AddError",
    "AddExecutionError",
    "AddInputError",
    "AddMemoriesResult",
    "AddStorageError",
    "AddedMemoryResult",
    "EmbeddedContextResult",
    "EmbeddedMemoryResult",
    "EmbedPlacementResult",
    "EmbedAuthorityError",
    "EmbedConflictError",
    "EmbedContextError",
    "EmbedError",
    "EmbedExecutionError",
    "EmbedInputError",
    "EmbedStorageError",
    "AtomizeGroundingApplyResult",
    "AtomizeGroundingConflictError",
    "AtomizeGroundingContextError",
    "AtomizeGroundingError",
    "AtomizeGroundingExecutionError",
    "AtomizeGroundingInputError",
    "AtomizeGroundingProposalResult",
    "AtomizeGroundingProviderFailure",
    "AtomizeGroundingQuestionResult",
    "AtomizeGroundingSessionResult",
    "AtomizeGroundingStorageError",
    "AtomizeAnalysisResult",
    "AtomizeAppliedItemResult",
    "AtomizeChildResult",
    "AtomizeConflictError",
    "AtomizeContextError",
    "AtomizeError",
    "AtomizeExecutionError",
    "AtomizeInputError",
    "AtomizeIssueResult",
    "AtomizeItemResult",
    "AtomizeOverviewResult",
    "AtomizeOverviewSectionResult",
    "AtomizeProviderFailure",
    "AtomizeReadingResult",
    "AtomizeReviewUpdateResult",
    "AtomizeReviewedApplyResult",
    "AtomizeSaveAsApplyResult",
    "AtomizeStorageError",
    "AtomizeStructuralApplyResult",
    "CompareAuthorityError",
    "CompareConflictError",
    "CompareContextError",
    "CompareError",
    "CompareExecutionError",
    "CompareInputError",
    "CompareProviderFailure",
    "CompareStorageError",
    "ComparisonFrameResult",
    "ComparisonIssueResult",
    "ComparisonMemberResult",
    "ComparisonOptionResult",
    "ComparisonRelationResult",
    "ComparisonReportsResult",
    "ComparisonResult",
    "DedupApplyResult",
    "DedupComponentResult",
    "DedupEvidenceResult",
    "DedupMemberResult",
    "DedupPlanResult",
    "DedunApplyResult",
    "DedunComponentResult",
    "DedunEvidenceResult",
    "DedunMemberResult",
    "DedunPlanResult",
    "ExactDedupGroupResult",
    "ExactDedupResult",
    "ExactDuplicateFindResult",
    "GrantedQueryResult",
    "HelpCatalogResult",
    "HelpComparisonOptionResult",
    "HelpComparisonResult",
    "HelpDetailCatalogResult",
    "HelpDetailReferenceResult",
    "HelpDetailResult",
    "HelpTextDetailResult",
    "HelpError",
    "HelpInputError",
    "MemCommitClient",
    "MemCommitError",
    "MeldApplyResult",
    "MeldAuthorityError",
    "MeldConflictError",
    "MeldContextError",
    "MeldError",
    "MeldExecutionError",
    "MeldInputError",
    "MeldIssueResult",
    "MeldOptionResult",
    "MeldProposalResult",
    "MeldProviderFailure",
    "MeldSessionResult",
    "MeldStorageError",
    "MemoryReferenceResult",
    "ContextReferenceResult",
    "OrdinaryQueryResult",
    "OperationHelpResult",
    "QueryAuthorityError",
    "QueryCatalogEntry",
    "QueryCitation",
    "QueryConfigurationError",
    "QueryContextError",
    "QueryError",
    "QueryExecutionError",
    "QueryInputError",
    "QueryProviderConfig",
    "QueryProviderFailure",
    "QueryStorageError",
    "QualityFindResult",
    "QualityFindingHandoff",
    "QualityFindingReviewDraft",
    "QualityFindingSource",
    "ReferenceQueryResult",
    "ReferenceConflictError",
    "ReferenceContextError",
    "ReferenceError",
    "ReferenceExecutionError",
    "ReferenceInputError",
    "ReferenceStorageError",
    "ReplaceApplyReceipt",
    "ReplaceAuthorityError",
    "ReplaceCheckpointResult",
    "ReplaceConflictError",
    "ReplaceContextError",
    "ReplaceContextPlanResult",
    "ReplaceError",
    "ReplaceExecutionError",
    "ReplaceInputError",
    "ReplaceMemoryPlanResult",
    "ReplacePlanResult",
    "ReplaceSpanResult",
    "ReplaceStorageError",
    "ResolveAnalysisResult",
    "ResolveApplyResult",
    "ResolveCandidateResult",
    "ResolveEffectResult",
    "ResolveIssueResult",
    "SearchItemResult",
    "SearchResult",
    "DistillApplyResult",
    "DistillProposal",
    "DistillRuleProposal",
    "ElaborateCaseProposal",
    "ElaborateProposal",
    "ElaborateRuleCheckProposal",
    "ElaborateRuleProposal",
    "ElaborateTargetContextItemProposal",
    "FitJudgmentResult",
    "FitPropositionInput",
    "ForgetApplyResult",
    "ForgetAuthorityError",
    "ForgetCandidateResult",
    "ForgetConflictError",
    "ForgetContextError",
    "ForgetError",
    "ForgetExecutionError",
    "ForgetInputError",
    "ForgetProviderFailure",
    "ForgetReviewResult",
    "ForgetStorageError",
    "FindAuthorityError",
    "FindContextError",
    "FindError",
    "FindExecutionError",
    "FindInputError",
    "FindMatchResult",
    "FindResult",
    "FindSpanResult",
    "FindStorageError",
    "SemanticAuthorityError",
    "SemanticConflictError",
    "SemanticContextError",
    "SemanticError",
    "SemanticExecutionError",
    "SemanticInputError",
    "SemanticProviderFailure",
    "SemanticStorageError",
    "ShowAuthorityError",
    "ShowContextError",
    "ShowContextResult",
    "ShowDirectItemResult",
    "ShowEmbeddedContextResult",
    "ShowError",
    "ShowExecutionError",
    "ShowInputError",
    "ShowMemoryReferenceResult",
    "ShowMemoryResult",
    "ShowQueryViewResult",
    "ShowResult",
    "ShowSourceResult",
    "ShowStorageError",
]


_LAZY_EXPORTS = {
    "AddMemoriesResult": ("memcommit.api.add", "AddMemoriesResult"),
    "AddedMemoryResult": ("memcommit.api.add", "AddedMemoryResult"),
    "EmbeddedContextResult": ("memcommit.api.embed", "EmbeddedContextResult"),
    "EmbeddedMemoryResult": ("memcommit.api.embed", "EmbeddedMemoryResult"),
    "EmbedPlacementResult": ("memcommit.api.embed", "EmbedPlacementResult"),
    "MemoryReferenceResult": (
        "memcommit.api.reference",
        "MemoryReferenceResult",
    ),
    "ContextReferenceResult": (
        "memcommit.api.reference",
        "ContextReferenceResult",
    ),
    **{
        name: ("memcommit.api.atomize", name)
        for name in (
            "AtomizeAnalysisResult",
            "AtomizeAppliedItemResult",
            "AtomizeChildResult",
            "AtomizeIssueResult",
            "AtomizeItemResult",
            "AtomizeOverviewResult",
            "AtomizeOverviewSectionResult",
            "AtomizeReadingResult",
            "AtomizeReviewUpdateResult",
            "AtomizeReviewedApplyResult",
            "AtomizeSaveAsApplyResult",
            "AtomizeStructuralApplyResult",
        )
    },
    "AtomizeGroundingApplyResult": (
        "memcommit.api.atomize_grounding",
        "AtomizeGroundingApplyResult",
    ),
    "AtomizeGroundingProposalResult": (
        "memcommit.api.atomize_grounding",
        "AtomizeGroundingProposalResult",
    ),
    "AtomizeGroundingQuestionResult": (
        "memcommit.api.atomize_grounding",
        "AtomizeGroundingQuestionResult",
    ),
    "AtomizeGroundingSessionResult": (
        "memcommit.api.atomize_grounding",
        "AtomizeGroundingSessionResult",
    ),
    "MemCommitClient": ("memcommit.api.client", "MemCommitClient"),
    "HelpCatalogResult": ("memcommit.api.help", "HelpCatalogResult"),
    "HelpComparisonOptionResult": (
        "memcommit.api.help",
        "HelpComparisonOptionResult",
    ),
    "HelpComparisonResult": ("memcommit.api.help", "HelpComparisonResult"),
    "HelpDetailCatalogResult": ("memcommit.api.help", "HelpDetailCatalogResult"),
    "HelpDetailReferenceResult": (
        "memcommit.api.help",
        "HelpDetailReferenceResult",
    ),
    "HelpDetailResult": ("memcommit.api.help", "HelpDetailResult"),
    "HelpTextDetailResult": ("memcommit.api.help", "HelpTextDetailResult"),
    "OperationHelpResult": ("memcommit.api.help", "OperationHelpResult"),
    **{
        name: ("memcommit.api.show", name)
        for name in (
            "ShowContextResult",
            "ShowDirectItemResult",
            "ShowEmbeddedContextResult",
            "ShowMemoryReferenceResult",
            "ShowMemoryResult",
            "ShowQueryViewResult",
            "ShowResult",
            "ShowSourceResult",
        )
    },
    **{
        f"Comparison{name}": ("memcommit.api.compare", f"Comparison{name}")
        for name in (
            "FrameResult",
            "IssueResult",
            "MemberResult",
            "OptionResult",
            "RelationResult",
            "ReportsResult",
            "Result",
        )
    },
    "MeldApplyResult": ("memcommit.api.meld", "MeldApplyResult"),
    "MeldIssueResult": ("memcommit.api.meld", "MeldIssueResult"),
    "MeldOptionResult": ("memcommit.api.meld", "MeldOptionResult"),
    "MeldProposalResult": ("memcommit.api.meld", "MeldProposalResult"),
    "MeldSessionResult": ("memcommit.api.meld", "MeldSessionResult"),
    **{
        name: ("memcommit.api.dedup", name)
        for name in (
            "DedupApplyResult",
            "DedupComponentResult",
            "DedupEvidenceResult",
            "DedupMemberResult",
            "DedupPlanResult",
            "DedunApplyResult",
            "DedunComponentResult",
            "DedunEvidenceResult",
            "DedunMemberResult",
            "DedunPlanResult",
            "ExactDedupGroupResult",
            "ExactDedupResult",
            "ExactDuplicateFindResult",
        )
    },
    "GrantedQueryResult": ("memcommit.api.query", "GrantedQueryResult"),
    "OrdinaryQueryResult": ("memcommit.api.query", "OrdinaryQueryResult"),
    "QueryCatalogEntry": ("memcommit.api.query", "QueryCatalogEntry"),
    "QueryCitation": ("memcommit.api.query", "QueryCitation"),
    "QueryProviderConfig": ("memcommit.api.query", "QueryProviderConfig"),
    "ReferenceQueryResult": ("memcommit.api.query", "ReferenceQueryResult"),
    **{
        name: ("memcommit.api.replace", name)
        for name in (
            "ReplaceApplyReceipt",
            "ReplaceCheckpointResult",
            "ReplaceContextPlanResult",
            "ReplaceMemoryPlanResult",
            "ReplacePlanResult",
            "ReplaceSpanResult",
        )
    },
    "FindMatchResult": ("memcommit.api.find", "FindMatchResult"),
    "FindResult": ("memcommit.api.find", "FindResult"),
    "FindSpanResult": ("memcommit.api.find", "FindSpanResult"),
    "SearchItemResult": ("memcommit.api.search", "SearchItemResult"),
    "SearchResult": ("memcommit.api.search", "SearchResult"),
    "QualityFindResult": ("memcommit.api.quality_find", "QualityFindResult"),
    **{
        name: ("memcommit.quality_finding_handoff", name)
        for name in (
            "QualityFindingHandoff",
            "QualityFindingReviewDraft",
            "QualityFindingSource",
        )
    },
    "ResolveAnalysisResult": ("memcommit.api.resolve", "ResolveAnalysisResult"),
    "ResolveApplyResult": ("memcommit.api.resolve", "ResolveApplyResult"),
    "ResolveCandidateResult": ("memcommit.api.resolve", "ResolveCandidateResult"),
    "ResolveEffectResult": ("memcommit.api.resolve", "ResolveEffectResult"),
    "ResolveIssueResult": ("memcommit.api.resolve", "ResolveIssueResult"),
    "DistillApplyResult": ("memcommit.api.semantic", "DistillApplyResult"),
    "DistillProposal": ("memcommit.api.semantic", "DistillProposal"),
    "DistillRuleProposal": ("memcommit.api.semantic", "DistillRuleProposal"),
    "ElaborateCaseProposal": ("memcommit.api.semantic", "ElaborateCaseProposal"),
    "ElaborateProposal": ("memcommit.api.semantic", "ElaborateProposal"),
    "ElaborateRuleCheckProposal": (
        "memcommit.api.semantic",
        "ElaborateRuleCheckProposal",
    ),
    "ElaborateRuleProposal": ("memcommit.api.semantic", "ElaborateRuleProposal"),
    "ElaborateTargetContextItemProposal": (
        "memcommit.api.semantic",
        "ElaborateTargetContextItemProposal",
    ),
    "FitJudgmentResult": ("memcommit.api.semantic", "FitJudgmentResult"),
    "FitPropositionInput": ("memcommit.api.semantic", "FitPropositionInput"),
    "ForgetApplyResult": ("memcommit.api.forget", "ForgetApplyResult"),
    "ForgetCandidateResult": ("memcommit.api.forget", "ForgetCandidateResult"),
    "ForgetReviewResult": ("memcommit.api.forget", "ForgetReviewResult"),
    **{
        name: ("memcommit.api.errors", name)
        for name in __all__
        if name.endswith("Error") or name.endswith("Failure")
    },
}


def __getattr__(name: str):
    try:
        module_name, attribute_name = _LAZY_EXPORTS[name]
    except KeyError as error:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        ) from error
    value = getattr(import_module(module_name), attribute_name)
    # Cache the real public object, not a proxy, so identity remains stable.
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
