"""MemoryStore, Grant, checkpoint, recovery, and provider adapters for Meld.

The package preserves the ``meld.runtime`` API while assigning Source access,
preparation, proposal iteration, and Apply transactions to explicit owners.
"""

from .apply_transaction import (
    MemoryStoreMeldApplyPort,
    affected_meld_owners as affected_meld_owners,
    apply_owner_proposals as apply_owner_proposals,
    execute_meld_apply,
    expected_owner_memories as expected_owner_memories,
    expected_target_memories as expected_target_memories,
    granted_owner_name as granted_owner_name,
    meld_checkpoint_record as meld_checkpoint_record,
    recover_meld_application as recover_meld_application,
    recover_owner_aware_application as recover_owner_aware_application,
    required_directional_target_permissions as required_directional_target_permissions,
    validate_owner_aware_grant_permissions as validate_owner_aware_grant_permissions,
)
from .preparation import (
    MemoryStoreMeldRestartPort as MemoryStoreMeldRestartPort,
    MemoryStoreMeldStartPort,
    PreparedMeldExecution,
    _start_relation_analysis as _start_relation_analysis,
    execute_meld_restart,
    execute_meld_start,
    prepare_meld_restart,
    prepare_meld_start,
)
from .proposal_iteration import (
    MELD_AGGREGATE_TIMEOUT_SECONDS,
    MemoryStoreMeldAssessmentPort,
    PreparedMeldTurnExecution,
    connect_meld_provider,
    execute_meld_assessment,
    execute_meld_turn,
    execute_prepared_meld_turn,
    prepare_meld_assessment,
    prepare_meld_turn_execution,
    prepare_pending_meld_turn,
)
from .session_repository import (
    MemoryStoreMeldDestinationPort,
    MemoryStoreMeldPreservationPort,
    MemoryStoreMeldSessionRepository,
    execute_meld_destination_change,
    execute_meld_initial_preservation,
    execute_meld_preservation,
    execute_meld_session_defer,
    execute_meld_session_open,
)
from .source_access import (
    assert_meld_non_target_source_bindings,
    assert_meld_source_bindings,
    assert_unapplied_meld_target,
    load_bound_meld_contexts,
    load_local_meld_source,
    load_meld_source,
    meld_bound_frame_digest,
    target_save_source_bindings as target_save_source_bindings,
    walk_meld_target_contexts as walk_meld_target_contexts,
)

__all__ = (
    "MELD_AGGREGATE_TIMEOUT_SECONDS",
    "MemoryStoreMeldApplyPort",
    "MemoryStoreMeldAssessmentPort",
    "MemoryStoreMeldDestinationPort",
    "MemoryStoreMeldPreservationPort",
    "MemoryStoreMeldSessionRepository",
    "MemoryStoreMeldStartPort",
    "PreparedMeldExecution",
    "PreparedMeldTurnExecution",
    "assert_meld_non_target_source_bindings",
    "assert_meld_source_bindings",
    "assert_unapplied_meld_target",
    "execute_meld_apply",
    "execute_meld_assessment",
    "execute_meld_destination_change",
    "execute_meld_initial_preservation",
    "execute_meld_preservation",
    "execute_meld_session_defer",
    "execute_meld_session_open",
    "execute_meld_start",
    "execute_meld_restart",
    "execute_meld_turn",
    "execute_prepared_meld_turn",
    "load_bound_meld_contexts",
    "load_local_meld_source",
    "load_meld_source",
    "meld_bound_frame_digest",
    "prepare_meld_assessment",
    "prepare_meld_restart",
    "prepare_meld_start",
    "prepare_meld_turn_execution",
    "prepare_pending_meld_turn",
    "connect_meld_provider",
)
