"""Machine-readable adapters over stable MemCommit application facades."""

from memcommit.interfaces.agent.add import (
    ADD_AGENT_CONTRACT_VERSION,
    ADD_AGENT_ERROR_MESSAGE_LIMIT,
    ADD_AGENT_TOOL_NAME,
    AddAgentAdapter,
    add_agent_tool_schema,
)
from memcommit.interfaces.agent.atomize_grounding import (
    ATOMIZE_GROUNDING_AGENT_CONTRACT_VERSION,
    ATOMIZE_GROUNDING_AGENT_TOOL_NAME,
    AtomizeGroundingAgentAdapter,
    AtomizeGroundingAgentKind,
    atomize_grounding_agent_tool_schema,
)
from memcommit.interfaces.agent.atomize import (
    ATOMIZE_AGENT_CONTRACT_VERSION,
    ATOMIZE_AGENT_TOOL_NAME,
    AtomizeAgentAdapter,
    AtomizeAgentKind,
    atomize_agent_tool_schema,
)
from memcommit.interfaces.agent.compare import (
    COMPARE_AGENT_CONTRACT_VERSION,
    COMPARE_AGENT_TOOL_NAME,
    CompareAgentAdapter,
    CompareAgentKind,
    compare_agent_tool_schema,
)
from memcommit.interfaces.agent.query import (
    QUERY_AGENT_CONTRACT_VERSION,
    QUERY_AGENT_ERROR_MESSAGE_LIMIT,
    QUERY_AGENT_TOOL_NAME,
    QueryAgentAdapter,
    query_agent_tool_schema,
)
from memcommit.interfaces.agent.quality_find import (
    QUALITY_FIND_AGENT_CONTRACT_VERSION,
    QUALITY_FIND_AGENT_TOOL_NAME,
    QualityFindAgentAdapter,
    quality_find_agent_tool_schema,
    quality_finding_handoff_agent_schema,
)
from memcommit.interfaces.agent.distill import (
    DISTILL_AGENT_CONTRACT_VERSION,
    DISTILL_AGENT_TOOL_NAME,
    DistillAgentAdapter,
    distill_agent_tool_schema,
)
from memcommit.interfaces.agent.dedup import (
    DEDUP_AGENT_CONTRACT_VERSION,
    DEDUP_AGENT_TOOL_NAME,
    DedupAgentAdapter,
    DedupAgentKind,
    dedup_agent_tool_schema,
)
from memcommit.interfaces.agent.elaborate import (
    ELABORATE_AGENT_CONTRACT_VERSION,
    ELABORATE_AGENT_TOOL_NAME,
    ElaborateAgentAdapter,
    elaborate_agent_tool_schema,
)
from memcommit.interfaces.agent.fit import (
    FIT_AGENT_CONTRACT_VERSION,
    FIT_AGENT_TOOL_NAME,
    FitAgentAdapter,
    fit_agent_tool_schema,
)
from memcommit.interfaces.agent.forget import (
    FORGET_AGENT_CONTRACT_VERSION,
    FORGET_AGENT_REVIEW_LIMIT,
    FORGET_AGENT_TOOL_NAME,
    ForgetAgentAdapter,
    ForgetAgentKind,
    forget_agent_tool_schema,
)
from memcommit.interfaces.agent.help import (
    HELP_AGENT_CONTRACT_VERSION,
    HELP_AGENT_TOOL_NAME,
    HelpAgentAdapter,
    HelpAgentKind,
    help_agent_tool_schema,
)
from memcommit.interfaces.agent.show import (
    SHOW_AGENT_CONTRACT_VERSION,
    SHOW_AGENT_TOOL_NAME,
    ShowAgentAdapter,
    ShowAgentKind,
    show_agent_tool_schema,
)
from memcommit.interfaces.agent.search import (
    SEARCH_AGENT_CONTRACT_VERSION,
    SEARCH_AGENT_TOOL_NAME,
    SearchAgentAdapter,
    SearchAgentKind,
    search_agent_tool_schema,
)
from memcommit.interfaces.agent.find import (
    FIND_AGENT_CONTRACT_VERSION,
    FIND_AGENT_TOOL_NAME,
    FindAgentAdapter,
    FindAgentKind,
    find_agent_tool_schema,
)
from memcommit.interfaces.agent.replace import (
    REPLACE_AGENT_CONTRACT_VERSION,
    REPLACE_AGENT_TOOL_NAME,
    ReplaceAgentAdapter,
    ReplaceAgentKind,
    replace_agent_tool_schema,
)
from memcommit.interfaces.agent.registry import (
    AGENT_TOOL_REGISTRY_VERSION,
    AgentToolBinding,
    AgentToolRegistrationError,
    AgentToolRegistry,
    build_default_agent_tool_registry,
)
from memcommit.interfaces.agent.resolve import (
    RESOLVE_AGENT_CONTRACT_VERSION,
    RESOLVE_AGENT_TOOL_NAME,
    ResolveAgentAdapter,
    ResolveAgentKind,
    resolve_agent_tool_schema,
)
from memcommit.interfaces.agent.meld import (
    MELD_AGENT_CONTRACT_VERSION,
    MELD_AGENT_TOOL_NAME,
    MeldAgentAdapter,
    MeldAgentKind,
    meld_agent_tool_schema,
)

__all__ = [
    "ADD_AGENT_CONTRACT_VERSION",
    "ADD_AGENT_ERROR_MESSAGE_LIMIT",
    "ADD_AGENT_TOOL_NAME",
    "AGENT_TOOL_REGISTRY_VERSION",
    "ATOMIZE_AGENT_CONTRACT_VERSION",
    "ATOMIZE_AGENT_TOOL_NAME",
    "ATOMIZE_GROUNDING_AGENT_CONTRACT_VERSION",
    "ATOMIZE_GROUNDING_AGENT_TOOL_NAME",
    "AddAgentAdapter",
    "AgentToolBinding",
    "AgentToolRegistrationError",
    "AgentToolRegistry",
    "AtomizeAgentAdapter",
    "AtomizeAgentKind",
    "AtomizeGroundingAgentAdapter",
    "AtomizeGroundingAgentKind",
    "COMPARE_AGENT_CONTRACT_VERSION",
    "COMPARE_AGENT_TOOL_NAME",
    "CompareAgentAdapter",
    "CompareAgentKind",
    "MELD_AGENT_CONTRACT_VERSION",
    "MELD_AGENT_TOOL_NAME",
    "MeldAgentAdapter",
    "MeldAgentKind",
    "DISTILL_AGENT_CONTRACT_VERSION",
    "DISTILL_AGENT_TOOL_NAME",
    "DistillAgentAdapter",
    "DEDUP_AGENT_CONTRACT_VERSION",
    "DEDUP_AGENT_TOOL_NAME",
    "DedupAgentAdapter",
    "DedupAgentKind",
    "ELABORATE_AGENT_CONTRACT_VERSION",
    "ELABORATE_AGENT_TOOL_NAME",
    "ElaborateAgentAdapter",
    "FIT_AGENT_CONTRACT_VERSION",
    "FIT_AGENT_TOOL_NAME",
    "FitAgentAdapter",
    "FORGET_AGENT_CONTRACT_VERSION",
    "FORGET_AGENT_REVIEW_LIMIT",
    "FORGET_AGENT_TOOL_NAME",
    "FIND_AGENT_CONTRACT_VERSION",
    "FIND_AGENT_TOOL_NAME",
    "FindAgentAdapter",
    "FindAgentKind",
    "REPLACE_AGENT_CONTRACT_VERSION",
    "REPLACE_AGENT_TOOL_NAME",
    "ReplaceAgentAdapter",
    "ReplaceAgentKind",
    "ForgetAgentAdapter",
    "ForgetAgentKind",
    "HELP_AGENT_CONTRACT_VERSION",
    "HELP_AGENT_TOOL_NAME",
    "HelpAgentAdapter",
    "HelpAgentKind",
    "QUERY_AGENT_CONTRACT_VERSION",
    "QUERY_AGENT_ERROR_MESSAGE_LIMIT",
    "QUERY_AGENT_TOOL_NAME",
    "QueryAgentAdapter",
    "QUALITY_FIND_AGENT_CONTRACT_VERSION",
    "QUALITY_FIND_AGENT_TOOL_NAME",
    "QualityFindAgentAdapter",
    "SHOW_AGENT_CONTRACT_VERSION",
    "SHOW_AGENT_TOOL_NAME",
    "ShowAgentAdapter",
    "ShowAgentKind",
    "SEARCH_AGENT_CONTRACT_VERSION",
    "SEARCH_AGENT_TOOL_NAME",
    "SearchAgentAdapter",
    "SearchAgentKind",
    "RESOLVE_AGENT_CONTRACT_VERSION",
    "RESOLVE_AGENT_TOOL_NAME",
    "ResolveAgentAdapter",
    "ResolveAgentKind",
    "add_agent_tool_schema",
    "atomize_agent_tool_schema",
    "atomize_grounding_agent_tool_schema",
    "build_default_agent_tool_registry",
    "compare_agent_tool_schema",
    "meld_agent_tool_schema",
    "distill_agent_tool_schema",
    "dedup_agent_tool_schema",
    "elaborate_agent_tool_schema",
    "fit_agent_tool_schema",
    "forget_agent_tool_schema",
    "find_agent_tool_schema",
    "replace_agent_tool_schema",
    "help_agent_tool_schema",
    "query_agent_tool_schema",
    "quality_find_agent_tool_schema",
    "quality_finding_handoff_agent_schema",
    "resolve_agent_tool_schema",
    "show_agent_tool_schema",
    "search_agent_tool_schema",
]
